// DO NOT EDIT. generated by github.com/tinywasm/ormc

package editorial

import (
	"github.com/tinywasm/model"
	"github.com/tinywasm/orm"
)

type Post struct {
	Id string
	TenantId string
	AuthorId string
	Slug string
	Title string
	Excerpt string
	Body string
	CoverImage string
	State int64
	PublishedAt int64
	CreatedAt int64
	UpdatedAt int64
}

func (m *Post) ModelName() string { return "Post" }

func (m *Post) Schema() []model.Field { return PostModel.Fields }

func (m *Post) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.AuthorId, &m.Slug, &m.Title, &m.Excerpt, &m.Body, &m.CoverImage, &m.State, &m.PublishedAt, &m.CreatedAt, &m.UpdatedAt} }

func (m *Post) IsNil() bool { return m == nil }

func (m *Post) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("tenant_id", m.TenantId)
	w.String("author_id", m.AuthorId)
	w.String("slug", m.Slug)
	w.String("title", m.Title)
	w.String("excerpt", m.Excerpt)
	w.String("body", m.Body)
	w.String("cover_image", m.CoverImage)
	w.Int("state", m.State)
	if m.PublishedAt != 0 { w.Int("published_at", m.PublishedAt) }
	w.Int("created_at", m.CreatedAt)
	w.Int("updated_at", m.UpdatedAt)
}

func (m *Post) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("author_id"); ok { m.AuthorId = v }
	if v, ok := r.String("slug"); ok { m.Slug = v }
	if v, ok := r.String("title"); ok { m.Title = v }
	if v, ok := r.String("excerpt"); ok { m.Excerpt = v }
	if v, ok := r.String("body"); ok { m.Body = v }
	if v, ok := r.String("cover_image"); ok { m.CoverImage = v }
	if v, ok := r.Int("state"); ok { m.State = v }
	if v, ok := r.Int("published_at"); ok { m.PublishedAt = v }
	if v, ok := r.Int("created_at"); ok { m.CreatedAt = v }
	if v, ok := r.Int("updated_at"); ok { m.UpdatedAt = v }
}

type PostList []*Post

func (s *PostList) Schema() []model.Field { return nil }
func (s *PostList) Pointers() []any     { return nil }
func (s *PostList) Len() int             { return len(*s) }
func (s *PostList) At(i int) model.Fielder { return (*s)[i] }
func (s *PostList) Append() model.Fielder  { v := &Post{}; *s = append(*s, v); return v }
func (s *PostList) IsNil() bool          { return s == nil }
func (s *PostList) EncodeFields(_ model.FieldWriter) {}
func (s *PostList) DecodeFields(_ model.FieldReader) {}

func (m *Post) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Post_ = struct {
	Id string
	TenantId string
	AuthorId string
	Slug string
	Title string
	Excerpt string
	Body string
	CoverImage string
	State string
	PublishedAt string
	CreatedAt string
	UpdatedAt string
}{
	Id: "id",
	TenantId: "tenant_id",
	AuthorId: "author_id",
	Slug: "slug",
	Title: "title",
	Excerpt: "excerpt",
	Body: "body",
	CoverImage: "cover_image",
	State: "state",
	PublishedAt: "published_at",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

func ReadOnePost(qb *orm.QB, model *Post) (*Post, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllPost(qb *orm.QB) (PostList, error) {
	var results PostList
	err := qb.ReadAll(
		func() model.Model { return &Post{} },
		func(m model.Model) { results = append(results, m.(*Post)) },
	)
	return results, err
}

type PostTransition struct {
	Id string
	TenantId string
	PostId string
	FromState int64
	ToState int64
	ActorId string
	Reason string
	At int64
}

func (m *PostTransition) ModelName() string { return "PostTransition" }

func (m *PostTransition) Schema() []model.Field { return PostTransitionModel.Fields }

func (m *PostTransition) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.PostId, &m.FromState, &m.ToState, &m.ActorId, &m.Reason, &m.At} }

func (m *PostTransition) IsNil() bool { return m == nil }

func (m *PostTransition) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("tenant_id", m.TenantId)
	w.String("post_id", m.PostId)
	w.Int("from_state", m.FromState)
	w.Int("to_state", m.ToState)
	w.String("actor_id", m.ActorId)
	if m.Reason != "" { w.String("reason", m.Reason) }
	w.Int("at", m.At)
}

func (m *PostTransition) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("post_id"); ok { m.PostId = v }
	if v, ok := r.Int("from_state"); ok { m.FromState = v }
	if v, ok := r.Int("to_state"); ok { m.ToState = v }
	if v, ok := r.String("actor_id"); ok { m.ActorId = v }
	if v, ok := r.String("reason"); ok { m.Reason = v }
	if v, ok := r.Int("at"); ok { m.At = v }
}

type PostTransitionList []*PostTransition

func (s *PostTransitionList) Schema() []model.Field { return nil }
func (s *PostTransitionList) Pointers() []any     { return nil }
func (s *PostTransitionList) Len() int             { return len(*s) }
func (s *PostTransitionList) At(i int) model.Fielder { return (*s)[i] }
func (s *PostTransitionList) Append() model.Fielder  { v := &PostTransition{}; *s = append(*s, v); return v }
func (s *PostTransitionList) IsNil() bool          { return s == nil }
func (s *PostTransitionList) EncodeFields(_ model.FieldWriter) {}
func (s *PostTransitionList) DecodeFields(_ model.FieldReader) {}

func (m *PostTransition) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var PostTransition_ = struct {
	Id string
	TenantId string
	PostId string
	FromState string
	ToState string
	ActorId string
	Reason string
	At string
}{
	Id: "id",
	TenantId: "tenant_id",
	PostId: "post_id",
	FromState: "from_state",
	ToState: "to_state",
	ActorId: "actor_id",
	Reason: "reason",
	At: "at",
}

func ReadOnePostTransition(qb *orm.QB, model *PostTransition) (*PostTransition, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllPostTransition(qb *orm.QB) (PostTransitionList, error) {
	var results PostTransitionList
	err := qb.ReadAll(
		func() model.Model { return &PostTransition{} },
		func(m model.Model) { results = append(results, m.(*PostTransition)) },
	)
	return results, err
}

func (m *PostTransition) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: PostTransitionModel.Fields[2], Ref: "post", RefColumn: "id", OnDelete: ""},
	}
}

type Publication struct {
	Id string
	TenantId string
	PostId string
	Channel string
	ExternalRef string
	PublishedAt int64
}

func (m *Publication) ModelName() string { return "Publication" }

func (m *Publication) Schema() []model.Field { return PublicationModel.Fields }

func (m *Publication) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.PostId, &m.Channel, &m.ExternalRef, &m.PublishedAt} }

func (m *Publication) IsNil() bool { return m == nil }

func (m *Publication) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("tenant_id", m.TenantId)
	w.String("post_id", m.PostId)
	w.String("channel", m.Channel)
	if m.ExternalRef != "" { w.String("external_ref", m.ExternalRef) }
	w.Int("published_at", m.PublishedAt)
}

func (m *Publication) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("post_id"); ok { m.PostId = v }
	if v, ok := r.String("channel"); ok { m.Channel = v }
	if v, ok := r.String("external_ref"); ok { m.ExternalRef = v }
	if v, ok := r.Int("published_at"); ok { m.PublishedAt = v }
}

type PublicationList []*Publication

func (s *PublicationList) Schema() []model.Field { return nil }
func (s *PublicationList) Pointers() []any     { return nil }
func (s *PublicationList) Len() int             { return len(*s) }
func (s *PublicationList) At(i int) model.Fielder { return (*s)[i] }
func (s *PublicationList) Append() model.Fielder  { v := &Publication{}; *s = append(*s, v); return v }
func (s *PublicationList) IsNil() bool          { return s == nil }
func (s *PublicationList) EncodeFields(_ model.FieldWriter) {}
func (s *PublicationList) DecodeFields(_ model.FieldReader) {}

func (m *Publication) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Publication_ = struct {
	Id string
	TenantId string
	PostId string
	Channel string
	ExternalRef string
	PublishedAt string
}{
	Id: "id",
	TenantId: "tenant_id",
	PostId: "post_id",
	Channel: "channel",
	ExternalRef: "external_ref",
	PublishedAt: "published_at",
}

func ReadOnePublication(qb *orm.QB, model *Publication) (*Publication, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllPublication(qb *orm.QB) (PublicationList, error) {
	var results PublicationList
	err := qb.ReadAll(
		func() model.Model { return &Publication{} },
		func(m model.Model) { results = append(results, m.(*Publication)) },
	)
	return results, err
}

func (m *Publication) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: PublicationModel.Fields[2], Ref: "post", RefColumn: "id", OnDelete: ""},
	}
}

type ListPostsArgs struct {
	TenantId string
	State int64
	AuthorId string
	Limit int64
	Offset int64
}

func (m *ListPostsArgs) ModelName() string { return "ListPostsArgs" }

func (m *ListPostsArgs) Schema() []model.Field { return ListPostsArgsModel.Fields }

func (m *ListPostsArgs) Pointers() []any { return []any{&m.TenantId, &m.State, &m.AuthorId, &m.Limit, &m.Offset} }

func (m *ListPostsArgs) IsNil() bool { return m == nil }

func (m *ListPostsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	if m.State != 0 { w.Int("state", m.State) }
	if m.AuthorId != "" { w.String("author_id", m.AuthorId) }
	w.Int("limit", m.Limit)
	w.Int("offset", m.Offset)
}

func (m *ListPostsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.Int("state"); ok { m.State = v }
	if v, ok := r.String("author_id"); ok { m.AuthorId = v }
	if v, ok := r.Int("limit"); ok { m.Limit = v }
	if v, ok := r.Int("offset"); ok { m.Offset = v }
}

type ListPostsArgsList []*ListPostsArgs

func (s *ListPostsArgsList) Schema() []model.Field { return nil }
func (s *ListPostsArgsList) Pointers() []any     { return nil }
func (s *ListPostsArgsList) Len() int             { return len(*s) }
func (s *ListPostsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListPostsArgsList) Append() model.Fielder  { v := &ListPostsArgs{}; *s = append(*s, v); return v }
func (s *ListPostsArgsList) IsNil() bool          { return s == nil }
func (s *ListPostsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListPostsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListPostsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetPostArgs struct {
	TenantId string
	Id string
}

func (m *GetPostArgs) ModelName() string { return "GetPostArgs" }

func (m *GetPostArgs) Schema() []model.Field { return GetPostArgsModel.Fields }

func (m *GetPostArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *GetPostArgs) IsNil() bool { return m == nil }

func (m *GetPostArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *GetPostArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type GetPostArgsList []*GetPostArgs

func (s *GetPostArgsList) Schema() []model.Field { return nil }
func (s *GetPostArgsList) Pointers() []any     { return nil }
func (s *GetPostArgsList) Len() int             { return len(*s) }
func (s *GetPostArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetPostArgsList) Append() model.Fielder  { v := &GetPostArgs{}; *s = append(*s, v); return v }
func (s *GetPostArgsList) IsNil() bool          { return s == nil }
func (s *GetPostArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetPostArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetPostArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type DeletePostArgs struct {
	TenantId string
	Id string
}

func (m *DeletePostArgs) ModelName() string { return "DeletePostArgs" }

func (m *DeletePostArgs) Schema() []model.Field { return DeletePostArgsModel.Fields }

func (m *DeletePostArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *DeletePostArgs) IsNil() bool { return m == nil }

func (m *DeletePostArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeletePostArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type DeletePostArgsList []*DeletePostArgs

func (s *DeletePostArgsList) Schema() []model.Field { return nil }
func (s *DeletePostArgsList) Pointers() []any     { return nil }
func (s *DeletePostArgsList) Len() int             { return len(*s) }
func (s *DeletePostArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *DeletePostArgsList) Append() model.Fielder  { v := &DeletePostArgs{}; *s = append(*s, v); return v }
func (s *DeletePostArgsList) IsNil() bool          { return s == nil }
func (s *DeletePostArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeletePostArgsList) DecodeFields(_ model.FieldReader) {}

func (m *DeletePostArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type PostActionArgs struct {
	TenantId string
	PostId string
	ActorId string
}

func (m *PostActionArgs) ModelName() string { return "PostActionArgs" }

func (m *PostActionArgs) Schema() []model.Field { return PostActionArgsModel.Fields }

func (m *PostActionArgs) Pointers() []any { return []any{&m.TenantId, &m.PostId, &m.ActorId} }

func (m *PostActionArgs) IsNil() bool { return m == nil }

func (m *PostActionArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("post_id", m.PostId)
	w.String("actor_id", m.ActorId)
}

func (m *PostActionArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("post_id"); ok { m.PostId = v }
	if v, ok := r.String("actor_id"); ok { m.ActorId = v }
}

type PostActionArgsList []*PostActionArgs

func (s *PostActionArgsList) Schema() []model.Field { return nil }
func (s *PostActionArgsList) Pointers() []any     { return nil }
func (s *PostActionArgsList) Len() int             { return len(*s) }
func (s *PostActionArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *PostActionArgsList) Append() model.Fielder  { v := &PostActionArgs{}; *s = append(*s, v); return v }
func (s *PostActionArgsList) IsNil() bool          { return s == nil }
func (s *PostActionArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *PostActionArgsList) DecodeFields(_ model.FieldReader) {}

func (m *PostActionArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type RequestChangesArgs struct {
	TenantId string
	PostId string
	ActorId string
	Reason string
}

func (m *RequestChangesArgs) ModelName() string { return "RequestChangesArgs" }

func (m *RequestChangesArgs) Schema() []model.Field { return RequestChangesArgsModel.Fields }

func (m *RequestChangesArgs) Pointers() []any { return []any{&m.TenantId, &m.PostId, &m.ActorId, &m.Reason} }

func (m *RequestChangesArgs) IsNil() bool { return m == nil }

func (m *RequestChangesArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("post_id", m.PostId)
	w.String("actor_id", m.ActorId)
	w.String("reason", m.Reason)
}

func (m *RequestChangesArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("post_id"); ok { m.PostId = v }
	if v, ok := r.String("actor_id"); ok { m.ActorId = v }
	if v, ok := r.String("reason"); ok { m.Reason = v }
}

type RequestChangesArgsList []*RequestChangesArgs

func (s *RequestChangesArgsList) Schema() []model.Field { return nil }
func (s *RequestChangesArgsList) Pointers() []any     { return nil }
func (s *RequestChangesArgsList) Len() int             { return len(*s) }
func (s *RequestChangesArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *RequestChangesArgsList) Append() model.Fielder  { v := &RequestChangesArgs{}; *s = append(*s, v); return v }
func (s *RequestChangesArgsList) IsNil() bool          { return s == nil }
func (s *RequestChangesArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *RequestChangesArgsList) DecodeFields(_ model.FieldReader) {}

func (m *RequestChangesArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListPublicationsArgs struct {
	TenantId string
	PostId string
	Channel string
}

func (m *ListPublicationsArgs) ModelName() string { return "ListPublicationsArgs" }

func (m *ListPublicationsArgs) Schema() []model.Field { return ListPublicationsArgsModel.Fields }

func (m *ListPublicationsArgs) Pointers() []any { return []any{&m.TenantId, &m.PostId, &m.Channel} }

func (m *ListPublicationsArgs) IsNil() bool { return m == nil }

func (m *ListPublicationsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	if m.PostId != "" { w.String("post_id", m.PostId) }
	if m.Channel != "" { w.String("channel", m.Channel) }
}

func (m *ListPublicationsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("post_id"); ok { m.PostId = v }
	if v, ok := r.String("channel"); ok { m.Channel = v }
}

type ListPublicationsArgsList []*ListPublicationsArgs

func (s *ListPublicationsArgsList) Schema() []model.Field { return nil }
func (s *ListPublicationsArgsList) Pointers() []any     { return nil }
func (s *ListPublicationsArgsList) Len() int             { return len(*s) }
func (s *ListPublicationsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListPublicationsArgsList) Append() model.Fielder  { v := &ListPublicationsArgs{}; *s = append(*s, v); return v }
func (s *ListPublicationsArgsList) IsNil() bool          { return s == nil }
func (s *ListPublicationsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListPublicationsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListPublicationsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListTransitionsArgs struct {
	TenantId string
	PostId string
}

func (m *ListTransitionsArgs) ModelName() string { return "ListTransitionsArgs" }

func (m *ListTransitionsArgs) Schema() []model.Field { return ListTransitionsArgsModel.Fields }

func (m *ListTransitionsArgs) Pointers() []any { return []any{&m.TenantId, &m.PostId} }

func (m *ListTransitionsArgs) IsNil() bool { return m == nil }

func (m *ListTransitionsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("post_id", m.PostId)
}

func (m *ListTransitionsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("post_id"); ok { m.PostId = v }
}

type ListTransitionsArgsList []*ListTransitionsArgs

func (s *ListTransitionsArgsList) Schema() []model.Field { return nil }
func (s *ListTransitionsArgsList) Pointers() []any     { return nil }
func (s *ListTransitionsArgsList) Len() int             { return len(*s) }
func (s *ListTransitionsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListTransitionsArgsList) Append() model.Fielder  { v := &ListTransitionsArgs{}; *s = append(*s, v); return v }
func (s *ListTransitionsArgsList) IsNil() bool          { return s == nil }
func (s *ListTransitionsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListTransitionsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListTransitionsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
